import { db } from "./db";
import { companies, layoffEvents } from "@shared/schema";
import { nanoid } from "nanoid";

// Fortune 500 companies data with employee counts, revenue, and comprehensive details
const fortune500Companies = [
  {
    name: "Walmart",
    industry: "General Merchandisers",
    location: "Bentonville, AR",
    country: "United States",
    website: "walmart.com",
    headcount: 2100000,
    revenue: "$681,000,000,000",
    ceo: "Douglas McMillon",
    founded: "1962",
    companyType: "Public" as const,
    marketCap: "$680B",
    ticker: "WMT",
    exchange: "NYSE"
  },
  {
    name: "Amazon",
    industry: "Internet Services and Retailing",
    location: "Seattle, WA", 
    country: "United States",
    website: "amazon.com",
    headcount: 1556000,
    revenue: "$638,000,000,000",
    ceo: "Andrew Jassy",
    founded: "1994",
    companyType: "Public" as const,
    marketCap: "$1.9T",
    ticker: "AMZN",
    exchange: "NASDAQ"
  },
  {
    name: "UnitedHealth Group",
    industry: "Health Care: Insurance and Managed Care",
    location: "Eden Prairie, MN",
    country: "United States", 
    website: "unitedhealthgroup.com",
    headcount: 400000,
    revenue: "$400,300,000,000",
    ceo: "Stephen Hemsley",
    founded: "1977",
    companyType: "Public" as const,
    marketCap: "$510B",
    ticker: "UNH",
    exchange: "NYSE"
  },
  {
    name: "Apple",
    industry: "Computers, Office Equipment",
    location: "Cupertino, CA",
    country: "United States",
    website: "apple.com", 
    headcount: 164000,
    revenue: "$391,000,000,000",
    ceo: "Timothy Cook",
    founded: "1976",
    companyType: "Public" as const,
    marketCap: "$3.7T",
    ticker: "AAPL", 
    exchange: "NASDAQ"
  },
  {
    name: "CVS Health",
    industry: "Health Care: Pharmacy and Other Services",
    location: "Woonsocket, RI",
    country: "United States",
    website: "cvshealth.com",
    headcount: 259500,
    revenue: "$372,800,000,000", 
    ceo: "David Joyner",
    founded: "1963",
    companyType: "Public" as const,
    marketCap: "$85B",
    ticker: "CVS",
    exchange: "NYSE"
  },
  {
    name: "Berkshire Hathaway",
    industry: "Insurance: Property and Casualty",
    location: "Omaha, NE",
    country: "United States",
    website: "berkshirehathaway.com",
    headcount: 392400,
    revenue: "$371,400,000,000",
    ceo: "Warren Buffett",
    founded: "1839",
    companyType: "Public" as const,
    marketCap: "$1.0T",
    ticker: "BRK.A",
    exchange: "NYSE"
  },
  {
    name: "Alphabet",
    industry: "Internet Services and Retailing",
    location: "Mountain View, CA",
    country: "United States",
    website: "abc.xyz",
    headcount: 183300,
    revenue: "$350,000,000,000",
    ceo: "Sundar Pichai", 
    founded: "1998",
    companyType: "Public" as const,
    marketCap: "$2.3T",
    ticker: "GOOGL",
    exchange: "NASDAQ"
  },
  {
    name: "Exxon Mobil",
    industry: "Petroleum Refining",
    location: "Spring, TX",
    country: "United States",
    website: "exxonmobil.com",
    headcount: 60900,
    revenue: "$349,600,000,000",
    ceo: "Darren Woods",
    founded: "1999",
    companyType: "Public" as const,
    marketCap: "$520B",
    ticker: "XOM",
    exchange: "NYSE"
  },
  {
    name: "McKesson",
    industry: "Wholesalers: Health Care", 
    location: "Irving, TX",
    country: "United States",
    website: "mckesson.com",
    headcount: 48000,
    revenue: "$309,000,000,000",
    ceo: "Brian Tyler",
    founded: "1833", 
    companyType: "Public" as const,
    marketCap: "$74B",
    ticker: "MCK",
    exchange: "NYSE"
  },
  {
    name: "Cencora",
    industry: "Wholesalers: Health Care",
    location: "Conshohocken, PA", 
    country: "United States",
    website: "cencora.com",
    headcount: 44000,
    revenue: "$294,000,000,000",
    ceo: "Robert Mauch",
    founded: "1985",
    companyType: "Public" as const,
    marketCap: "$53B",
    ticker: "COR",
    exchange: "NYSE"
  },
  {
    name: "JPMorgan Chase",
    industry: "Commercial Banks",
    location: "New York, NY",
    country: "United States",
    website: "jpmorganchase.com",
    headcount: 317200,
    revenue: "$278,900,000,000",
    ceo: "James Dimon",
    founded: "2000",
    companyType: "Public" as const,
    marketCap: "$650B",
    ticker: "JPM",
    exchange: "NYSE"
  },
  {
    name: "Costco",
    industry: "General Merchandisers", 
    location: "Issaquah, WA",
    country: "United States",
    website: "costco.com",
    headcount: 333000,
    revenue: "$254,500,000,000",
    ceo: "Ron Vachris",
    founded: "1983",
    companyType: "Public" as const,
    marketCap: "$410B",
    ticker: "COST",
    exchange: "NASDAQ"
  },
  {
    name: "Cigna",
    industry: "Health Care: Pharmacy and Other Services",
    location: "Bloomfield, CT",
    country: "United States",
    website: "thecignagroup.com",
    headcount: 72400,
    revenue: "$247,100,000,000",
    ceo: "David Cordani",
    founded: "1982",
    companyType: "Public" as const,
    marketCap: "$110B",
    ticker: "CI",
    exchange: "NYSE"
  },
  {
    name: "Microsoft",
    industry: "Computer Software",
    location: "Redmond, WA",
    country: "United States",
    website: "microsoft.com",
    headcount: 228000,
    revenue: "$245,100,000,000",
    ceo: "Satya Nadella",
    founded: "1975",
    companyType: "Public" as const,
    marketCap: "$3.2T",
    ticker: "MSFT",
    exchange: "NASDAQ"
  },
  {
    name: "Cardinal Health",
    industry: "Wholesalers: Health Care",
    location: "Dublin, OH",
    country: "United States",
    website: "cardinalhealth.com",
    headcount: 48400,
    revenue: "$226,800,000,000",
    ceo: "Jason Hollar",
    founded: "1971",
    companyType: "Public" as const,
    marketCap: "$32B",
    ticker: "CAH",
    exchange: "NYSE"
  },
  {
    name: "Chevron",
    industry: "Petroleum Refining",
    location: "San Ramon, CA",
    country: "United States",
    website: "chevron.com",
    headcount: 45300,
    revenue: "$202,800,000,000",
    ceo: "Michael Wirth",
    founded: "1879",
    companyType: "Public" as const,
    marketCap: "$290B",
    ticker: "CVX",
    exchange: "NYSE"
  },
  {
    name: "Bank of America",
    industry: "Commercial Banks",
    location: "Charlotte, NC",
    country: "United States",
    website: "bankofamerica.com",
    headcount: 213200,
    revenue: "$192,400,000,000",
    ceo: "Brian Moynihan",
    founded: "1998",
    companyType: "Public" as const,
    marketCap: "$325B",
    ticker: "BAC",
    exchange: "NYSE"
  },
  {
    name: "General Motors",
    industry: "Motor Vehicles & Parts",
    location: "Detroit, MI",
    country: "United States",
    website: "gm.com",
    headcount: 162000,
    revenue: "$187,400,000,000",
    ceo: "Mary Barra",
    founded: "1908",
    companyType: "Public" as const,
    marketCap: "$68B",
    ticker: "GM",
    exchange: "NYSE"
  },
  {
    name: "Ford Motor",
    industry: "Motor Vehicles & Parts",
    location: "Dearborn, MI",
    country: "United States",
    website: "ford.com",
    headcount: 171000,
    revenue: "$185,000,000,000",
    ceo: "James Farley Jr.",
    founded: "1903",
    companyType: "Public" as const,
    marketCap: "$45B",
    ticker: "F",
    exchange: "NYSE"
  },
  {
    name: "Elevance Health",
    industry: "Health Care: Insurance and Managed Care",
    location: "Indianapolis, IN",
    country: "United States",
    website: "elevancehealth.com",
    headcount: 103700,
    revenue: "$177,000,000,000",
    ceo: "Gail Boudreaux",
    founded: "1944",
    companyType: "Public" as const,
    marketCap: "$86B",
    ticker: "ELV",
    exchange: "NYSE"
  },
  {
    name: "Citigroup",
    industry: "Commercial Banks",
    location: "New York, NY",
    country: "United States",
    website: "citigroup.com",
    headcount: 227900,
    revenue: "$170,800,000,000",
    ceo: "Jane Fraser",
    founded: "1998",
    companyType: "Public" as const,
    marketCap: "$145B",
    ticker: "C",
    exchange: "NYSE"
  },
  {
    name: "Meta",
    industry: "Internet Services and Retailing",
    location: "Menlo Park, CA",
    country: "United States",
    website: "meta.com",
    headcount: 74100,
    revenue: "$164,500,000,000",
    ceo: "Mark Zuckerberg",
    founded: "2004",
    companyType: "Public" as const,
    marketCap: "$1.4T",
    ticker: "META",
    exchange: "NASDAQ"
  },
  {
    name: "Centene",
    industry: "Health Care: Insurance and Managed Care",
    location: "St. Louis, MO",
    country: "United States",
    website: "centene.com",
    headcount: 60500,
    revenue: "$163,100,000,000",
    ceo: "Sarah London",
    founded: "1984",
    companyType: "Public" as const,
    marketCap: "$40B",
    ticker: "CNC",
    exchange: "NYSE"
  },
  {
    name: "Home Depot",
    industry: "Specialty Retailers: Other",
    location: "Atlanta, GA",
    country: "United States",
    website: "homedepot.com",
    headcount: 470100,
    revenue: "$159,500,000,000",
    ceo: "Edward Decker",
    founded: "1978",
    companyType: "Public" as const,
    marketCap: "$410B",
    ticker: "HD",
    exchange: "NYSE"
  },
  {
    name: "Fannie Mae",
    industry: "Diversified Financials",
    location: "Washington, DC",
    country: "United States",
    website: "fanniemae.com",
    headcount: 8200,
    revenue: "$152,700,000,000",
    ceo: "Priscilla Almodovar",
    founded: "1938",
    companyType: "Public" as const,
    marketCap: "$18B",
    ticker: "FNMA",
    exchange: "OTC"
  }
];

const additionalFortune500Companies = [
  {
    name: "Walgreens Boots Alliance",
    industry: "Food & Drug Stores",
    location: "Deerfield, IL",
    country: "United States",
    website: "walgreensbootsalliance.com",
    headcount: 252500,
    revenue: "$147,700,000,000",
    ceo: "Timothy Wentworth",
    founded: "2014",
    companyType: "Public" as const,
    marketCap: "$9B",
    ticker: "WBA",
    exchange: "NASDAQ"
  },
  {
    name: "Kroger",
    industry: "Food & Drug Stores",
    location: "Cincinnati, OH",
    country: "United States",
    website: "thekrogerco.com",
    headcount: 409000,
    revenue: "$147,100,000,000",
    ceo: "Rodney McMullen",
    founded: "1883",
    companyType: "Public" as const,
    marketCap: "$45B",
    ticker: "KR",
    exchange: "NYSE"
  },
  {
    name: "Phillips 66",
    industry: "Petroleum Refining",
    location: "Houston, TX",
    country: "United States",
    website: "phillips66.com",
    headcount: 13200,
    revenue: "$145,500,000,000",
    ceo: "Mark Lashier",
    founded: "2012",
    companyType: "Public" as const,
    marketCap: "$65B",
    ticker: "PSX",
    exchange: "NYSE"
  },
  {
    name: "Marathon Petroleum",
    industry: "Petroleum Refining",
    location: "Findlay, OH",
    country: "United States",
    website: "marathonpetroleum.com",
    headcount: 18300,
    revenue: "$140,400,000,000",
    ceo: "Maryann Mannen",
    founded: "2011",
    companyType: "Public" as const,
    marketCap: "$72B",
    ticker: "MPC",
    exchange: "NYSE"
  },
  {
    name: "Verizon Communications",
    industry: "Telecommunications",
    location: "New York, NY", 
    country: "United States",
    website: "verizon.com",
    headcount: 99600,
    revenue: "$134,800,000,000",
    ceo: "Hans Vestberg",
    founded: "2000",
    companyType: "Public" as const,
    marketCap: "$175B",
    ticker: "VZ",
    exchange: "NYSE"
  },
  {
    name: "NVIDIA",
    industry: "Semiconductors and Other Electronic Components",
    location: "Santa Clara, CA",
    country: "United States",
    website: "nvidia.com",
    headcount: 36000,
    revenue: "$130,500,000,000",
    ceo: "Jensen Huang",
    founded: "1993",
    companyType: "Public" as const,
    marketCap: "$3.5T",
    ticker: "NVDA",
    exchange: "NASDAQ"
  },
  {
    name: "Goldman Sachs",
    industry: "Investment Banking & Brokerage",
    location: "New York, NY",
    country: "United States",
    website: "goldmansachs.com",
    headcount: 46500,
    revenue: "$126,900,000,000",
    ceo: "David Solomon",
    founded: "1869",
    companyType: "Public" as const,
    marketCap: "$160B",
    ticker: "GS",
    exchange: "NYSE"
  },
  {
    name: "Wells Fargo",
    industry: "Commercial Banks",
    location: "San Francisco, CA",
    country: "United States",
    website: "wellsfargo.com",
    headcount: 217500,
    revenue: "$125,400,000,000",
    ceo: "Charles Scharf",
    founded: "1852",
    companyType: "Public" as const,
    marketCap: "$210B",
    ticker: "WFC",
    exchange: "NYSE"
  },
  {
    name: "Valero Energy",
    industry: "Petroleum Refining",
    location: "San Antonio, TX",
    country: "United States",
    website: "valero.com",
    headcount: 9900,
    revenue: "$124,000,000,000",
    ceo: "Lane Riggs",
    founded: "1980",
    companyType: "Public" as const,
    marketCap: "$55B",
    ticker: "VLO",
    exchange: "NYSE"
  },
  {
    name: "Comcast",
    industry: "Telecommunications",
    location: "Philadelphia, PA",
    country: "United States",
    website: "comcast.com",
    headcount: 182000,
    revenue: "$123,700,000,000",
    ceo: "Brian Roberts",
    founded: "1963",
    companyType: "Public" as const,
    marketCap: "$185B",
    ticker: "CMCSA",
    exchange: "NASDAQ"
  },
  {
    name: "State Farm",
    industry: "Insurance: Property and Casualty",
    location: "Bloomington, IL",
    country: "United States",
    website: "statefarm.com",
    headcount: 67400,
    revenue: "$123,000,000,000",
    ceo: "Jon Farney",
    founded: "1922",
    companyType: "Mutual" as const,
    marketCap: "N/A",
    ticker: "N/A",
    exchange: "N/A"
  },
  {
    name: "AT&T",
    industry: "Telecommunications",
    location: "Dallas, TX",
    country: "United States",
    website: "att.com",
    headcount: 141000,
    revenue: "$122,300,000,000",
    ceo: "John Stankey",
    founded: "1983",
    companyType: "Public" as const,
    marketCap: "$155B",
    ticker: "T",
    exchange: "NYSE"
  },
  {
    name: "Freddie Mac",
    industry: "Diversified Financials", 
    location: "McLean, VA",
    country: "United States",
    website: "freddiemac.com",
    headcount: 8100,
    revenue: "$122,100,000,000",
    ceo: "Michael Hutchins",
    founded: "1970",
    companyType: "Public" as const,
    marketCap: "$8B",
    ticker: "FMCC",
    exchange: "OTC"
  },
  {
    name: "Humana",
    industry: "Health Care: Insurance and Managed Care",
    location: "Louisville, KY",
    country: "United States",
    website: "humana.com",
    headcount: 65700,
    revenue: "$117,800,000,000",
    ceo: "James Rechtin",
    founded: "1961",
    companyType: "Public" as const,
    marketCap: "$42B",
    ticker: "HUM",
    exchange: "NYSE"
  },
  {
    name: "Morgan Stanley",
    industry: "Investment Banking & Brokerage",
    location: "New York, NY",
    country: "United States",
    website: "morganstanley.com",
    headcount: 80500,
    revenue: "$107,300,000,000",
    ceo: "Edward Pick",
    founded: "1935",
    companyType: "Public" as const,
    marketCap: "$185B",
    ticker: "MS",
    exchange: "NYSE"
  },
  {
    name: "Target",
    industry: "General Merchandisers",
    location: "Minneapolis, MN",
    country: "United States",
    website: "target.com",
    headcount: 440000,
    revenue: "$106,600,000,000",
    ceo: "Brian Cornell",
    founded: "1902",
    companyType: "Public" as const,
    marketCap: "$68B",
    ticker: "TGT",
    exchange: "NYSE"
  },
  {
    name: "Tesla",
    industry: "Motor Vehicles & Parts",
    location: "Austin, TX",
    country: "United States",
    website: "tesla.com",
    headcount: 125700,
    revenue: "$97,700,000,000",
    ceo: "Elon Musk",
    founded: "2003",
    companyType: "Public" as const,
    marketCap: "$1.2T",
    ticker: "TSLA",
    exchange: "NASDAQ"
  },
  {
    name: "Dell Technologies",
    industry: "Computers, Office Equipment",
    location: "Round Rock, TX",
    country: "United States",
    website: "delltechnologies.com",
    headcount: 108000,
    revenue: "$95,600,000,000",
    ceo: "Michael Dell",
    founded: "1984",
    companyType: "Public" as const,
    marketCap: "$98B",
    ticker: "DELL",
    exchange: "NYSE"
  },
  {
    name: "PepsiCo",
    industry: "Beverages",
    location: "Purchase, NY",
    country: "United States",
    website: "pepsico.com",
    headcount: 319000,
    revenue: "$91,900,000,000",
    ceo: "Ramon Laguarta",
    founded: "1965",
    companyType: "Public" as const,
    marketCap: "$230B",
    ticker: "PEP",
    exchange: "NASDAQ"
  },
  {
    name: "Walt Disney",
    industry: "Entertainment",
    location: "Burbank, CA",
    country: "United States",
    website: "thewaltdisneycompany.com",
    headcount: 205000,
    revenue: "$91,400,000,000",
    ceo: "Robert Iger",
    founded: "1923",
    companyType: "Public" as const,
    marketCap: "$175B",
    ticker: "DIS",
    exchange: "NYSE"
  }
];

const moreFortune500Companies = [
  {
    name: "UPS",
    industry: "Mail, Package and Freight Delivery",
    location: "Atlanta, GA",
    country: "United States",
    website: "ups.com",
    headcount: 372200,
    revenue: "$91,100,000,000",
    ceo: "Carol Tomé",
    founded: "1907",
    companyType: "Public" as const,
    marketCap: "$130B",
    ticker: "UPS",
    exchange: "NYSE"
  },
  {
    name: "Johnson & Johnson",
    industry: "Pharmaceuticals",
    location: "New Brunswick, NJ",
    country: "United States",
    website: "jnj.com",
    headcount: 138100,
    revenue: "$88,800,000,000",
    ceo: "Joaquin Duato",
    founded: "1886",
    companyType: "Public" as const,
    marketCap: "$450B",
    ticker: "JNJ",
    exchange: "NYSE"
  },
  {
    name: "FedEx",
    industry: "Mail, Package and Freight Delivery",
    location: "Memphis, TN",
    country: "United States",
    website: "fedex.com",
    headcount: 422100,
    revenue: "$87,700,000,000",
    ceo: "Rajesh Subramaniam",
    founded: "1971",
    companyType: "Public" as const,
    marketCap: "$68B",
    ticker: "FDX",
    exchange: "NYSE"
  },
  {
    name: "Archer Daniels Midland",
    industry: "Food Production",
    location: "Chicago, IL",
    country: "United States",
    website: "adm.com",
    headcount: 43200,
    revenue: "$85,500,000,000",
    ceo: "Juan Luciano",
    founded: "1902",
    companyType: "Public" as const,
    marketCap: "$28B",
    ticker: "ADM",
    exchange: "NYSE"
  },
  {
    name: "Procter & Gamble",
    industry: "Household and Personal Products",
    location: "Cincinnati, OH",
    country: "United States",
    website: "pg.com",
    headcount: 108000,
    revenue: "$84,000,000,000",
    ceo: "Jon Moeller",
    founded: "1837",
    companyType: "Public" as const,
    marketCap: "$385B",
    ticker: "PG",
    exchange: "NYSE"
  },
  {
    name: "Lowe's",
    industry: "Specialty Retailers: Other",
    location: "Mooresville, NC",
    country: "United States",
    website: "lowes.com",
    headcount: 215500,
    revenue: "$83,700,000,000",
    ceo: "Marvin Ellison",
    founded: "1946",
    companyType: "Public" as const,
    marketCap: "$145B",
    ticker: "LOW",
    exchange: "NYSE"
  },
  {
    name: "RTX Corporation",
    industry: "Aerospace & Defense",
    location: "Arlington, VA",
    country: "United States",
    website: "rtx.com",
    headcount: 186000,
    revenue: "$80,700,000,000",
    ceo: "Christopher Calio",
    founded: "2020",
    companyType: "Public" as const,
    marketCap: "$125B",
    ticker: "RTX",
    exchange: "NYSE"
  },
  {
    name: "Albertsons",
    industry: "Food & Drug Stores",
    location: "Boise, ID",
    country: "United States",
    website: "albertsonscompanies.com",
    headcount: 196600,
    revenue: "$79,200,000,000",
    ceo: "Susan Morris",
    founded: "1939",
    companyType: "Public" as const,
    marketCap: "$12B",
    ticker: "ACI",
    exchange: "NYSE"
  },
  {
    name: "Sysco",
    industry: "Wholesalers: Food and Grocery",
    location: "Houston, TX",
    country: "United States",
    website: "sysco.com",
    headcount: 76000,
    revenue: "$78,800,000,000",
    ceo: "Kevin Hourican",
    founded: "1969",
    companyType: "Public" as const,
    marketCap: "$38B",
    ticker: "SYY",
    exchange: "NYSE"
  },
  {
    name: "Progressive",
    industry: "Insurance: Property and Casualty",
    location: "Mayfield Village, OH",
    country: "United States",
    website: "progressive.com",
    headcount: 66300,
    revenue: "$75,400,000,000",
    ceo: "Susan Patricia Griffith",
    founded: "1937",
    companyType: "Public" as const,
    marketCap: "$125B",
    ticker: "PGR",
    exchange: "NYSE"
  },
  {
    name: "American Express",
    industry: "Diversified Financials",
    location: "New York, NY",
    country: "United States",
    website: "americanexpress.com",
    headcount: 75100,
    revenue: "$74,200,000,000",
    ceo: "Stephen Squeri",
    founded: "1850",
    companyType: "Public" as const,
    marketCap: "$145B",
    ticker: "AXP",
    exchange: "NYSE"
  },
  {
    name: "Lockheed Martin",
    industry: "Aerospace & Defense",
    location: "Bethesda, MD",
    country: "United States",
    website: "lockheedmartin.com",
    headcount: 121000,
    revenue: "$71,000,000,000",
    ceo: "James Taiclet",
    founded: "1995",
    companyType: "Public" as const,
    marketCap: "$125B",
    ticker: "LMT",
    exchange: "NYSE"
  },
  {
    name: "MetLife",
    industry: "Insurance: Life, Health",
    location: "New York, NY",
    country: "United States",
    website: "metlife.com",
    headcount: 45000,
    revenue: "$71,000,000,000",
    ceo: "Michel Khalaf",
    founded: "1868",
    companyType: "Public" as const,
    marketCap: "$58B",
    ticker: "MET",
    exchange: "NYSE"
  },
  {
    name: "HCA Healthcare",
    industry: "Health Care: Medical Facilities",
    location: "Nashville, TN",
    country: "United States",
    website: "hcahealthcare.com",
    headcount: 271000,
    revenue: "$70,600,000,000",
    ceo: "Samuel Hazen",
    founded: "1968",
    companyType: "Public" as const,
    marketCap: "$85B",
    ticker: "HCA",
    exchange: "NYSE"
  },
  {
    name: "Prudential Financial",
    industry: "Insurance: Life, Health",
    location: "Newark, NJ",
    country: "United States",
    website: "prudential.com",
    headcount: 37900,
    revenue: "$70,400,000,000",
    ceo: "Andrew Sullivan",
    founded: "1875",
    companyType: "Public" as const,
    marketCap: "$45B",
    ticker: "PRU",
    exchange: "NYSE"
  },
  {
    name: "Boeing",
    industry: "Aerospace & Defense",
    location: "Chicago, IL",
    country: "United States",
    website: "boeing.com",
    headcount: 172000,
    revenue: "$66,500,000,000",
    ceo: "Kelly Ortberg",
    founded: "1916",
    companyType: "Public" as const,
    marketCap: "$105B",
    ticker: "BA",
    exchange: "NYSE"
  },
  {
    name: "Caterpillar",
    industry: "Construction and Farm Machinery",
    location: "Peoria, IL",
    country: "United States",
    website: "caterpillar.com",
    headcount: 112900,
    revenue: "$64,800,000,000",
    ceo: "Jim Umpleby",
    founded: "1925",
    companyType: "Public" as const,
    marketCap: "$165B",
    ticker: "CAT",
    exchange: "NYSE"
  },
  {
    name: "Merck",
    industry: "Pharmaceuticals",
    location: "Rahway, NJ",
    country: "United States",
    website: "merck.com",
    headcount: 74000,
    revenue: "$64,200,000,000",
    ceo: "Robert Davis",
    founded: "1891",
    companyType: "Public" as const,
    marketCap: "$320B",
    ticker: "MRK",
    exchange: "NYSE"
  },
  {
    name: "Allstate",
    industry: "Insurance: Property and Casualty",
    location: "Northbrook, IL",
    country: "United States",
    website: "allstate.com",
    headcount: 55200,
    revenue: "$64,100,000,000",
    ceo: "Thomas Wilson",
    founded: "1931",
    companyType: "Public" as const,
    marketCap: "$38B",
    ticker: "ALL",
    exchange: "NYSE"
  },
  {
    name: "Pfizer",
    industry: "Pharmaceuticals",
    location: "New York, NY",
    country: "United States",
    website: "pfizer.com",
    headcount: 81000,
    revenue: "$63,600,000,000",
    ceo: "Albert Bourla",
    founded: "1849",
    companyType: "Public" as const,
    marketCap: "$185B",
    ticker: "PFE",
    exchange: "NYSE"
  },
  {
    name: "IBM",
    industry: "Information Technology Services",
    location: "Armonk, NY",
    country: "United States",
    website: "ibm.com",
    headcount: 284500,
    revenue: "$62,800,000,000",
    ceo: "Arvind Krishna",
    founded: "1911",
    companyType: "Public" as const,
    marketCap: "$215B",
    ticker: "IBM",
    exchange: "NYSE"
  },
  {
    name: "Delta Air Lines",
    industry: "Airlines",
    location: "Atlanta, GA",
    country: "United States",
    website: "delta.com",
    headcount: 103000,
    revenue: "$61,600,000,000",
    ceo: "Edward Bastian",
    founded: "1924",
    companyType: "Public" as const,
    marketCap: "$28B",
    ticker: "DAL",
    exchange: "NYSE"
  },
  {
    name: "Publix Super Markets",
    industry: "Food & Drug Stores",
    location: "Lakeland, FL",
    country: "United States",
    website: "publix.com",
    headcount: 255000,
    revenue: "$60,200,000,000",
    ceo: "Kevin Murphy",
    founded: "1930",
    companyType: "Private" as const,
    marketCap: "N/A",
    ticker: "N/A",
    exchange: "N/A"
  },
  {
    name: "United Airlines",
    industry: "Airlines",
    location: "Chicago, IL",
    country: "United States",
    website: "united.com",
    headcount: 107300,
    revenue: "$57,100,000,000",
    ceo: "Scott Kirby",
    founded: "1926",
    companyType: "Public" as const,
    marketCap: "$18B",
    ticker: "UAL",
    exchange: "NASDAQ"
  },
  {
    name: "ConocoPhillips",
    industry: "Mining, Crude-Oil Production",
    location: "Houston, TX",
    country: "United States",
    website: "conocophillips.com",
    headcount: 11800,
    revenue: "$57,000,000,000",
    ceo: "Ryan Lance",
    founded: "2002",
    companyType: "Public" as const,
    marketCap: "$155B",
    ticker: "COP",
    exchange: "NYSE"
  }
];

// Combine all companies
const allFortune500Companies = [...fortune500Companies, ...additionalFortune500Companies, ...moreFortune500Companies];

export async function seedFortune500Companies() {
  console.log("Starting Fortune 500 companies seed...");
  
  try {
    // Clear existing companies to avoid duplicates
    console.log("Clearing existing companies...");
    await db.delete(companies);
    
    // Insert Fortune 500 companies
    console.log(`Inserting ${allFortune500Companies.length} Fortune 500 companies...`);
    
    for (const company of allFortune500Companies) {
      const companyData = {
        id: nanoid(),
        name: company.name,
        industry: company.industry,
        location: company.location,
        country: company.country,
        website: company.website,
        employeeCount: company.headcount.toLocaleString(), // Convert number to string format
        size: company.headcount >= 1000000 ? "Enterprise (1M+)" : 
              company.headcount >= 100000 ? "Large (100K+)" :
              company.headcount >= 10000 ? "Medium (10K+)" : "Small (<10K)",
        lastUpdate: new Date(),
        status: "safe"
      };
      
      await db.insert(companies).values(companyData);
      console.log(`✓ Added ${company.name} - ${company.headcount.toLocaleString()} employees`);
    }
    
    console.log(`\n🎉 Successfully seeded ${allFortune500Companies.length} Fortune 500 companies!`);
    console.log(`Total employees across Fortune 500: ${allFortune500Companies.reduce((sum, c) => sum + c.headcount, 0).toLocaleString()}`);
    
  } catch (error) {
    console.error("Error seeding Fortune 500 companies:", error);
    throw error;
  }
}

// Run if called directly (ES module compatible check)
if (import.meta.url === `file://${process.argv[1]}`) {
  seedFortune500Companies()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}